# Generated by Django 4.2.4 on 2023-12-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='utilisateur',
            new_name='user',
        ),
    ]
